name: Container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-container:
    name: "Build container image"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Work around Podman breakage
        run: |
          mkdir -vp ~/.config/containers
          echo -e "[storage.options]\nmount_program=\"/usr/bin/fuse-overlayfs\"" > ~/.config/containers/storage.conf
      - name: Build container image
        run: podman build .
